### ISSUE TITLE
Remove dependency on `eslint-config-airbnb` and `eslint-config-airbnb-typescript`

### ISSUE THREAD

**Issue by birdofpreyru** [birdofpreyru/react-utils#420]
It turns out (https://github.com/airbnb/javascript/issues/2961), despite its affiliation to AirBnB, `eslint-config-airbnb` is currently maintained by a single dude, not affiliated to the company, not doing a great maintenance job, and mistaken on priorities (https://github.com/airbnb/javascript/issues/3075). Thus, `eslint-config-airbnb` is an unreliable, toxic dependency that blocks our migration to the latest ESLint (#335) and other configs; we should get rid of this dependency ASAP.

**Comment by VedantAnand17** [comment]
I've fixed the changes in my PR, kindly check

**Comment by birdofpreyru** [comment]
Just removing AirBnB ESLint configs from `package.json` does not solve the problem 🤷‍♂ also, ESLint re-configuration for my projects isn't smth I trust others to do (as there is no good ways to validate the change beside doing it myself).

**Comment by birdofpreyru** [comment]
Completed in eee760b78d55ed906e092b05fada2bc1f55a0a50 (pending release for unrelated reasons). [eslint-configs](https://github.com/birdofpreyru/eslint-configs) is our brand new replacement for AirBnB configs.

**Comment by birdofpreyru** [comment]
Actually... we are still missing to update our docs for ESLint configs at https://dr.pogodin.studio/docs/react-utils/docs/api/configs/eslint
